openapi: 3.0.3
info:
  title: Easyapp API
  version: 1.0.0
  description: API documentation for easyapp
paths:
  /api/hello/:
    get:
      operationId: api_hello_retrieve
      description: Get a hello world message
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: ''
  /api/auth/register/:
    post:
      operationId: api_auth_register_create
      description: Регистрация нового пользователя (member)
      tags:
      - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '201':
          description: Успешная регистрация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Ошибка валидации данных регистрации
  /api/auth/login/:
    post:
      operationId: api_auth_login_create
      description: Авторизация пользователя (member)
      tags:
      - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Успешная авторизация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Неверное имя пользователя или пароль
  /api/auth/me/:
    get:
      operationId: api_auth_me_retrieve
      description: Получение данных текущего пользователя
      tags:
      - auth
      security:
      - TokenAuth: []
      responses:
        '200':
          description: Данные текущего пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
        '401':
          description: Не авторизован
  /api/auth/logout/:
    post:
      operationId: api_auth_logout_create
      description: Выход пользователя (удаление токена)
      tags:
      - auth
      security:
      - TokenAuth: []
      responses:
        '200':
          description: Успешный выход
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutResponse'
        '401':
          description: Не авторизован
components:
  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
          maxLength: 200
        timestamp:
          type: string
          format: date-time
          readOnly: true
      required:
      - message
      - timestamp
    Member:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          maxLength: 150
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - id
      - username
      - created_at
    AuthRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          format: password
      required:
      - username
      - password
    AuthResponse:
      type: object
      properties:
        member:
          $ref: '#/components/schemas/Member'
        token:
          type: string
      required:
      - member
      - token
    LogoutResponse:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    TokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Используйте формат: "Token <токен>"'
